services:
  db:
    image: postgres:17
    container_name: tiendaya-db
    environment:
      POSTGRES_DB: tiendaya
      POSTGRES_USER: tiendaya
      POSTGRES_PASSWORD: tiendaya123
    ports:
      - "5432:5432"
    volumes:
      - tiendaya_data:/var/lib/postgresql/data

    # pgadmin:
    # image: dpage/pgadmin4
    # container_name: tiendaya-pgadmin
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: tiendaya@example.com
    #   PGADMIN_DEFAULT_PASSWORD: tiendaya123
    # ports:
    #   - "5050:80"

volumes:
  tiendaya_data: