services:
  db:
    image: postgres:17
    container_name: tiendaya-db
    environment:
      POSTGRES_DB: tiendaya
      POSTGRES_USER: tiendaya
      POSTGRES_PASSWORD: tiendaya123
    ports:
      - "5432:5432"
    volumes:
      - tiendaya_data:/var/lib/postgresql/data

volumes:
  tiendaya_data: